### PR TITLE
Make code compile on Windows with VS Build Tools v17.13.6

### PR DESCRIPTION
**Pull request by KritzelKratzel**
Make code compile on Windows with VS Build Tools v17.13.6
- Added code to prevent MSVC from throwing error C2057
- Added some type casts to silence MSVC warnings
- Tweaked CMakeList files to work with MSVC flawlessly

### CODE REVIEW

**Comment by KritzelKratzel** [comment]
PR withdrawn.
